version: '3.4'

services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    container_name: products.api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
        - ConnectionStrings__default=server=products.database;port=3306;database=security_db;userid=root;password=flora110601
        - AppSettings__TokenSecret=31ad84457c906f687ef959ad5b9011c674aff6ed17b026294adc6d19fb8fb0d8
        - AppSettings__AdminPassword=flora110601
    depends_on: 
        - products.database

  products.database:
    image: mysql:latest
    container_name: products.database
    environment:
        - MYSQL_ROOT_PASSWORD=flora110601
        - MYSQL_DATABASE=security_db
    ports:
        - "3310:3306"
    volumes:
        - SECURITY:/var/lib/mysql

volumes:
  SECURITY:
  
