version: '3.4'

services:
  product.api:
    image: ${DOCKER_REGISTRY-}productsapi
    container_name: api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
        - ConnectionStrings__default=server=product.db;database=security_db;user id=SA;password=$MSSQL_SA_PASSWORD;TrustServerCertificate=true;
        - AppSettings__TokenSecret=$SECRET_STRING
    depends_on: 
        product.db:
            condition: service_healthy


  product.db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    container_name: database
    env_file: .env
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=$MSSQL_SA_PASSWORD
    ports:
        - "1440:1433"
    volumes:
        - MSSQL_SECURITY:/var/opt/mssql
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s

volumes:
    MSSQL_SECURITY:
